#!/bin/bash

echo "Application is starting..."
default_app_name="Spring"

echo "Application name is ${default_app_name}!"

# if
value=25
if (( value > 0 )); then
    echo "${value} is positive"
fi

value=-3
if (( value > 0 )); then
    echo "${value} is positive"
else
    echo "${value} is negative"
fi

value=0
if (( value > 0 )); then
    echo "${value} is positive"
elif (( value == 0 )); then
    echo "${value} is zero"
else
    echo "${value} is negative"
fi

array=(1 5 22 190 1240 2050)
echo "array[2]=${array[2]}"
echo "${array[@]}"
echo "size of array is ${#array[@]}"
array[2]=222
echo "${array[@]}"
array+=(10999 34)
echo "${array[@]}"

echo "Enter application name:"
read app_name

echo "New application name is ${app_name}!"

# case
case "${app_name}" in
clean)
    echo "Clean is invoked"
    ;;
build)
    echo "Build is invoked"
    ;;
*)
    echo "${app_name} is not supported by this application"
    exit 2
    ;;
esac
